// Single source of truth for the tool catalog.
// The oss-tech-write skill appends one entry here per documented tool; the sidebar
// (config.ts) and the homepage catalog (ToolCatalog.vue) both read from it.
//
// Product premise: the CNCF landscape is a wall of logos with no context. This catalog
// is the readable map: every entry links to a real deep-dive, grouped and labelled.

export type Maturity = 'Graduated' | 'Incubating' | 'Sandbox' | 'Archived' | 'Independent'

export interface ToolEntry {
  /** URL slug; must match docs/tools/<slug> and docs/ja/tools/<slug>. */
  slug: string
  /** Display name, e.g. "Argo CD". */
  name: string
  /** One-line English tagline shown on the catalog card. */
  tagline: string
  /** One-line Japanese tagline shown on the catalog card. */
  taglineJa: string
  /** Category. Must be one of CATEGORY_ORDER below. */
  category: string
  /** CNCF maturity (or "Independent" for non-CNCF projects). */
  maturity: Maturity
}

// Catalog sections, in display order. Mirrors the CNCF landscape but trimmed to the
// categories this site actually covers. Add a category here before using it.
export const CATEGORY_ORDER: string[] = [
  'Orchestration & Scheduling',
  'App Definition & GitOps',
  'Service Mesh & Networking',
  'API Gateway',
  'Observability',
  'Security & Compliance',
  'Identity & Policy',
  'Supply Chain',
  'Storage & Database',
  'Messaging & Streaming',
  'Runtime',
  'Container Registry',
  'Chaos Engineering',
  'Developer Tools',
]

export const tools: ToolEntry[] = [
  {
    slug: 'authelia',
    name: 'Authelia',
    tagline: 'SSO and 2FA for your reverse proxy, plus an OpenID Connect provider',
    taglineJa: 'リバースプロキシ向けの SSO と 2FA、加えて OpenID Connect プロバイダ',
    category: 'Identity & Policy',
    maturity: 'Independent',
  },
  {
    slug: 'openfga',
    name: 'OpenFGA',
    tagline: 'Zanzibar-style fine-grained authorization from relationship tuples and a declarative model',
    taglineJa: 'Zanzibar 系のきめ細かい認可。関係タプルと宣言的モデルで判定する',
    category: 'Identity & Policy',
    maturity: 'Incubating',
  },
  {
    slug: 'spicedb',
    name: 'SpiceDB',
    tagline: 'A Zanzibar-inspired permissions database that answers checks by traversing a relationship graph',
    taglineJa: '関係グラフを辿って認可判定を返す Zanzibar 由来のパーミッション DB',
    category: 'Identity & Policy',
    maturity: 'Independent',
  },
  {
    slug: 'permify',
    name: 'Permify',
    tagline: 'A Zanzibar-style authorization engine backed by relation tuples in PostgreSQL',
    taglineJa: 'PostgreSQL のリレーションタプルに基づく Zanzibar 系の認可エンジン',
    category: 'Identity & Policy',
    maturity: 'Independent',
  },
  {
    slug: 'authentik',
    name: 'authentik',
    tagline: 'A self-hosted identity provider: SSO, OAuth2/OIDC, SAML, and LDAP with a visual flow editor',
    taglineJa: 'SSO・OIDC・SAML・LDAP をまとめ、ビジュアルフローエディタを持つセルフホスト IdP',
    category: 'Identity & Policy',
    maturity: 'Independent',
  },
  {
    slug: 'zitadel',
    name: 'ZITADEL',
    tagline: 'API-first, event-sourced identity platform with multi-tenancy built in',
    taglineJa: 'API ファースト・イベントソーシングで、初期からマルチテナントな ID 基盤',
    category: 'Identity & Policy',
    maturity: 'Independent',
  },
  {
    slug: 'oauth2-proxy',
    name: 'OAuth2 Proxy',
    tagline: 'A reverse proxy that puts OAuth2/OIDC login in front of a service that has none',
    taglineJa: '認証を持たないサービスの前段に OAuth2/OIDC ログインを置くリバースプロキシ',
    category: 'Identity & Policy',
    maturity: 'Sandbox',
  },
  {
    slug: 'in-toto',
    name: 'in-toto',
    tagline: 'Verifies every step of a software supply chain was done as planned by authorized parties',
    taglineJa: 'サプライチェーンの各ステップが計画通り・権限者により実行されたか検証する',
    category: 'Supply Chain',
    maturity: 'Graduated',
  },
  {
    slug: 'tuf',
    name: 'The Update Framework (TUF)',
    tagline: 'Secures software update systems so a compromised repo or key cannot push malicious updates',
    taglineJa: 'リポジトリや鍵が侵害されても悪意ある更新を送り込めないよう更新システムを保護する',
    category: 'Supply Chain',
    maturity: 'Graduated',
  },
  {
    slug: 'guac',
    name: 'GUAC',
    tagline: 'Aggregates software supply chain metadata into a queryable graph',
    taglineJa: 'ソフトウェアサプライチェーンのメタデータをクエリ可能なグラフに集約する',
    category: 'Supply Chain',
    maturity: 'Independent',
  },
  { slug: 'argo', name: 'Argo CD', tagline: 'Pull-based GitOps continuous delivery for Kubernetes, reconciling cluster state against Git.', taglineJa: 'Git とクラスタ状態を突き合わせる、Kubernetes 向けの pull 型 GitOps 継続デリバリ。', category: 'App Definition & GitOps', maturity: 'Graduated' },
  { slug: 'cert-manager', name: 'cert-manager', tagline: 'Issues and renews X.509 certificates from ACME, Vault, Venafi, and private CAs as native Kubernetes resources.', taglineJa: 'ACME・Vault・Venafi・プライベート CA から X.509 証明書を発行・更新し、Kubernetes ネイティブなリソースとして扱う。', category: 'Security & Compliance', maturity: 'Graduated' },
  { slug: 'cilium', name: 'Cilium', tagline: 'eBPF-based networking, security, and observability for Kubernetes, with policy written against workload identity.', taglineJa: 'Kubernetes 向けの eBPF ベースのネットワーキング・セキュリティ・可観測性。ポリシーはワークロードの identity に対して書く。', category: 'Service Mesh & Networking', maturity: 'Graduated' },
  { slug: 'cloudevents', name: 'CloudEvents', tagline: 'A vendor-neutral specification for event data, with SDKs that carry events across HTTP, Kafka, and MQTT.', taglineJa: 'イベントデータのベンダー中立な仕様。SDK が HTTP・Kafka・MQTT 越しにイベントを運ぶ。', category: 'App Definition & GitOps', maturity: 'Graduated' },
  { slug: 'containerd', name: 'containerd', tagline: 'An OCI-compliant container runtime daemon, the runtime layer beneath Kubernetes and Docker.', taglineJa: 'Kubernetes や Docker の下回りでコンテナを実行する OCI 準拠のコンテナランタイムデーモン。', category: 'Runtime', maturity: 'Graduated' },
  { slug: 'coredns', name: 'CoreDNS', tagline: 'A DNS server that resolves each query through a configured chain of plugins; the default Kubernetes cluster DNS.', taglineJa: 'クエリを設定済みプラグインの連鎖に通して解決する DNS サーバ。Kubernetes の既定クラスタ DNS。', category: 'Service Mesh & Networking', maturity: 'Graduated' },
  { slug: 'cri-o', name: 'CRI-O', tagline: 'A lightweight, Kubernetes-only Container Runtime Interface implementation for running OCI containers.', taglineJa: 'Kubernetes 専用に絞った軽量な Container Runtime Interface 実装。OCI コンテナを動かす。', category: 'Runtime', maturity: 'Graduated' },
  { slug: 'crossplane', name: 'Crossplane', tagline: 'A Kubernetes control-plane framework: define your own APIs and reconcile cloud and in-cluster resources.', taglineJa: '自前の API を定義し、クラウドおよびクラスタ内リソースを reconcile する Kubernetes コントロールプレーン基盤。', category: 'App Definition & GitOps', maturity: 'Graduated' },
  { slug: 'cubefs', name: 'CubeFS', tagline: 'A distributed file and object store that separates metadata from data, per-volume replication or erasure coding.', taglineJa: 'メタデータとデータを分離し、ボリュームごとに複製かイレイジャーコーディングを選べる分散ストレージ。', category: 'Storage & Database', maturity: 'Graduated' },
  { slug: 'dapr', name: 'Dapr', tagline: 'A sidecar runtime giving any app portable building-block APIs for state, pub/sub, invocation, and actors.', taglineJa: '状態・pub/sub・サービス呼び出し・actor のビルディングブロック API を提供するサイドカー型ランタイム。', category: 'App Definition & GitOps', maturity: 'Graduated' },
  { slug: 'dragonfly', name: 'Dragonfly', tagline: 'Peer-to-peer distribution of container images, files, and AI models across large clusters.', taglineJa: 'コンテナイメージ・ファイル・AI モデルを大規模クラスタ全体で P2P 配布する。', category: 'Runtime', maturity: 'Graduated' },
  { slug: 'envoy', name: 'Envoy', tagline: 'An out-of-process L4/L7 proxy and universal data plane for polyglot microservices.', taglineJa: 'ポリグロットなマイクロサービスのための、アウトオブプロセスな L4/L7 プロキシかつユニバーサルデータプレーン。', category: 'Service Mesh & Networking', maturity: 'Graduated' },
  { slug: 'etcd', name: 'etcd', tagline: 'A distributed key-value store that uses Raft to keep a small, critical dataset consistent across a cluster.', taglineJa: 'Raft で小さく重要なデータをクラスタ全体で一貫させる分散キーバリューストア。', category: 'Storage & Database', maturity: 'Graduated' },
  { slug: 'falco', name: 'Falco', tagline: 'A runtime security engine that watches Linux kernel events and alerts when activity matches a rule.', taglineJa: 'Linux カーネルイベントを監視し、ルール一致時にアラートするランタイムセキュリティエンジン。', category: 'Security & Compliance', maturity: 'Graduated' },
  { slug: 'fluentd', name: 'Fluentd', tagline: 'A unified logging layer that collects events, routes them by tag, buffers, and ships them to many destinations.', taglineJa: '入力からイベントを集め、タグでルーティングし、バッファして多様な出力へ送る統合ロギング層。', category: 'Observability', maturity: 'Graduated' },
  { slug: 'flux', name: 'Flux', tagline: 'A GitOps tool that keeps a Kubernetes cluster continuously reconciled with manifests stored in Git.', taglineJa: 'Git のマニフェストと Kubernetes クラスタを継続的に一致させ続ける GitOps ツール。', category: 'App Definition & GitOps', maturity: 'Graduated' },
  { slug: 'harbor', name: 'Harbor', tagline: 'An OCI registry that adds RBAC, vulnerability scanning, replication, and signature verification.', taglineJa: 'RBAC・脆弱性スキャン・レプリケーション・署名検証を加えた OCI レジストリ。', category: 'Supply Chain', maturity: 'Graduated' },
  { slug: 'helm', name: 'Helm', tagline: 'The package manager for Kubernetes: bundle, version, and install related resources as a chart.', taglineJa: 'Kubernetes のパッケージマネージャ。関連リソースをチャートとしてまとめ、管理しインストールする。', category: 'App Definition & GitOps', maturity: 'Graduated' },
  { slug: 'istio', name: 'Istio', tagline: 'A service mesh that puts a programmable proxy next to every workload, moving traffic, mTLS, and telemetry out of app code.', taglineJa: '各ワークロードの隣にプロキシを置き、トラフィック管理・mTLS・テレメトリをアプリ外に出すサービスメッシュ。', category: 'Service Mesh & Networking', maturity: 'Graduated' },
  { slug: 'jaeger', name: 'Jaeger', tagline: 'A distributed tracing platform; in v2 it ships as an OpenTelemetry Collector distribution.', taglineJa: '分散トレーシング基盤。v2 では OpenTelemetry Collector のディストリビューションとして提供される。', category: 'Observability', maturity: 'Graduated' },
  { slug: 'keda', name: 'KEDA', tagline: 'Event-driven autoscaling for Kubernetes, including scale-to-zero, by feeding external events into the HPA.', taglineJa: '外部イベントを HPA に橋渡しし、ゼロスケール込みの Kubernetes イベント駆動オートスケールを実現する。', category: 'Orchestration & Scheduling', maturity: 'Graduated' },
  { slug: 'knative', name: 'Knative', tagline: 'Runs containers as request-driven serverless workloads on Kubernetes, including scale to zero.', taglineJa: 'コンテナを Kubernetes 上でリクエスト駆動のサーバーレスとして動かし、ゼロスケールも行う。', category: 'Orchestration & Scheduling', maturity: 'Graduated' },
  { slug: 'kubeedge', name: 'KubeEdge', tagline: 'Extends a Kubernetes control plane to edge nodes and IoT devices over unreliable networks.', taglineJa: '信頼できないネットワーク越しに Kubernetes をエッジノードと IoT デバイスへ延伸する。', category: 'Orchestration & Scheduling', maturity: 'Graduated' },
  { slug: 'kubernetes', name: 'Kubernetes', tagline: 'Run containers across many machines by declaring desired state; controllers drive the cluster toward it.', taglineJa: '望ましい状態を宣言すると、コントローラがクラスタをそこへ収束させるコンテナ基盤。', category: 'Orchestration & Scheduling', maturity: 'Graduated' },
  { slug: 'kyverno', name: 'Kyverno', tagline: 'A Kubernetes admission engine where each policy is itself a Kubernetes resource written as YAML.', taglineJa: 'ポリシーそのものが Kubernetes リソースで、YAML として書ける admission エンジン。', category: 'Security & Compliance', maturity: 'Graduated' },
  { slug: 'linkerd', name: 'Linkerd', tagline: 'A Kubernetes service mesh adding mTLS, metrics, and reliability through a lightweight Rust sidecar proxy.', taglineJa: '軽量な Rust 製サイドカーで mTLS・メトリクス・信頼性を足す Kubernetes サービスメッシュ。', category: 'Service Mesh & Networking', maturity: 'Graduated' },
  { slug: 'open-policy-agent', name: 'Open Policy Agent (OPA)', tagline: 'A general-purpose policy engine that decouples authorization from app code, evaluated via the Rego language.', taglineJa: '認可をアプリコードから切り離し、Rego 言語で評価する汎用ポリシーエンジン。', category: 'Identity & Policy', maturity: 'Graduated' },
  { slug: 'opentelemetry', name: 'OpenTelemetry', tagline: 'A vendor-neutral standard and toolchain for generating, collecting, and exporting traces, metrics, and logs.', taglineJa: 'トレース・メトリクス・ログを生成・収集・転送するベンダー中立な標準とツールチェーン。', category: 'Observability', maturity: 'Graduated' },
  { slug: 'prometheus', name: 'Prometheus', tagline: 'Metrics-based monitoring that pulls time series over HTTP, stores them in a local TSDB, and queries with PromQL.', taglineJa: '時系列を HTTP で pull し、ローカル TSDB に保存し、PromQL でクエリするメトリクス監視。', category: 'Observability', maturity: 'Graduated' },
  { slug: 'rook', name: 'Rook', tagline: 'A Kubernetes operator that runs Ceph as declarative custom resources for block, file, and object storage.', taglineJa: 'Ceph を宣言的なカスタムリソースとして運用し、ブロック・ファイル・オブジェクトを提供する Kubernetes オペレータ。', category: 'Storage & Database', maturity: 'Graduated' },
  { slug: 'spiffe', name: 'SPIFFE', tagline: 'Standards for giving workloads a short-lived, cryptographically verifiable identity without pre-shared secrets.', taglineJa: '秘密の事前共有なしに、ワークロードへ短命で暗号学的に検証可能な ID を与える標準群。', category: 'Identity & Policy', maturity: 'Graduated' },
  { slug: 'spire', name: 'SPIRE', tagline: 'Issues short-lived, attested workload identities (X509-SVID and JWT-SVID); the SPIFFE reference implementation.', taglineJa: '短命で attest 済みのワークロード ID (X509-SVID/JWT-SVID) を発行する SPIFFE 参照実装。', category: 'Identity & Policy', maturity: 'Graduated' },
  { slug: 'vitess', name: 'Vitess', tagline: 'A clustering system that shards MySQL horizontally behind a single MySQL-compatible endpoint.', taglineJa: 'MySQL を水平シャーディングし、単一の MySQL 互換エンドポイントの裏に隠すクラスタリングシステム。', category: 'Storage & Database', maturity: 'Graduated' },
  { slug: 'tikv', name: 'TiKV', tagline: 'A distributed, transactional key-value database, the storage layer behind TiDB.', taglineJa: 'TiDB の下回りを担う分散トランザクショナル・キーバリューデータベース。', category: 'Storage & Database', maturity: 'Graduated' },
  { slug: "artifact-hub", name: "Artifact Hub", tagline: "An open, CNCF-hosted index to find, install, and publish Cloud Native packages across more than two dozen artifact kinds.", taglineJa: "Helm チャートから OLM、Tekton まで 20 種類超の Cloud Native アーティファクトを横断で発見・導入・公開できる、CNCF 運営のオープンなインデックス。", category: "App Definition & GitOps", maturity: "Incubating" },
  { slug: "backstage", name: "Backstage", tagline: "A framework for building developer portals: a software catalog, templates, and docs assembled into one internal application you own.", taglineJa: "開発者ポータルを構築するためのフレームワーク。ソフトウェアカタログ・テンプレート・ドキュメントを、自分で所有する 1 つの社内アプリに組み上げる。", category: "Developer Tools", maturity: "Incubating" },
  { slug: "buildpacks", name: "Buildpacks", tagline: "Turn application source code into production-ready OCI images without writing a Dockerfile.", taglineJa: "Dockerfile を書かずに、アプリのソースコードを本番向け OCI イメージへ変換する。", category: "App Definition & GitOps", maturity: "Incubating" },
  { slug: "chaos-mesh", name: "Chaos Mesh", tagline: "A Kubernetes-native chaos engineering platform that injects faults into pods, networks, filesystems, and the kernel through custom resources.", taglineJa: "Pod・ネットワーク・ファイルシステム・カーネルへの障害をカスタムリソース経由で注入する、Kubernetes ネイティブのカオスエンジニアリングプラットフォーム。", category: "Chaos Engineering", maturity: "Incubating" },
  { slug: "cloud-custodian", name: "Cloud Custodian", tagline: "A YAML policy engine for cloud governance that queries resources, filters them, and runs actions like tagging, stopping, or deleting, so rules live as code instead of ad hoc scripts.", taglineJa: "クラウドガバナンスのための YAML ポリシーエンジン。リソースを照会してフィルタで絞り込み、タグ付け・停止・削除などのアクションを実行する。ルールを場当たり的なスクリプトではなくコードとして管理する。", category: "Security & Compliance", maturity: "Incubating" },
  { slug: "container-network-interface", name: "Container Network Interface (CNI)", tagline: "A minimal, runtime-agnostic spec plus Go libraries that let any container runtime hand pod networking to pluggable executables.", taglineJa: "コンテナランタイムが Pod のネットワーク設定を差し替え可能な実行ファイルに委譲するための、最小でランタイム非依存な仕様と Go ライブラリ。", category: "Service Mesh & Networking", maturity: "Incubating" },
  { slug: "contour", name: "Contour", tagline: "A Kubernetes ingress controller that programs Envoy as its data plane, translating Ingress, its HTTPProxy CRD, and Gateway API into live Envoy config over xDS.", taglineJa: "Envoy をデータプレーンとして駆動する Kubernetes Ingress コントローラ。Ingress・独自 HTTPProxy CRD・Gateway API を xDS 経由の Envoy 設定へ変換する。", category: "API Gateway", maturity: "Incubating" },
  { slug: "cortex", name: "Cortex", tagline: "A horizontally scalable, multi-tenant, long-term storage backend for Prometheus that receives metrics over remote write.", taglineJa: "Prometheus 向けの水平スケール可能でマルチテナントな長期ストレージ。メトリクスを remote write で受信する。", category: "Observability", maturity: "Incubating" },
  { slug: "emissary-ingress", name: "Emissary-Ingress", tagline: "Kubernetes-native API gateway and ingress built on Envoy Proxy, driven entirely by CRDs.", taglineJa: "Envoy Proxy を基盤に、CRD だけで設定する Kubernetes ネイティブな API ゲートウェイ兼 Ingress。", category: "API Gateway", maturity: "Incubating" },
  { slug: "flatcar-container-linux", name: "Flatcar Container Linux", tagline: "A minimal, immutable Linux distribution for running containers, with A/B partitions and atomic automatic updates.", taglineJa: "コンテナ実行に特化した最小・イミュータブルな Linux ディストリビューション。A/B パーティションとアトミックな自動更新を持つ。", category: "Runtime", maturity: "Incubating" },
  { slug: "fluid", name: "Fluid", tagline: "A Kubernetes operator that makes datasets a first-class resource and orchestrates distributed caches to speed up data access for AI and big-data workloads.", taglineJa: "データセットを Kubernetes の一級リソースに昇格させ、分散キャッシュをオーケストレーションして AI・ビッグデータのデータアクセスを高速化する Kubernetes オペレータ。", category: "Storage & Database", maturity: "Incubating" },
  { slug: "grpc", name: "gRPC", tagline: "A high-performance RPC framework that turns a Protocol Buffers service definition into typed clients and servers running over HTTP/2.", taglineJa: "Protocol Buffers のサービス定義から、HTTP/2 上で動く型付きクライアント・サーバを生成する高性能 RPC フレームワーク。", category: "Developer Tools", maturity: "Incubating" },
  { slug: "karmada", name: "Karmada", tagline: "Kubernetes-native control plane that propagates and schedules workloads across many clusters and clouds.", taglineJa: "複数クラスタ/クラウドへワークロードを Kubernetes ネイティブ API のまま配布・スケジューリングするコントロールプレーン。", category: "Orchestration & Scheduling", maturity: "Incubating" },
  { slug: "keycloak", name: "Keycloak", tagline: "Open-source identity and access management server speaking OIDC, OAuth 2.0, and SAML for apps and services.", taglineJa: "OIDC / OAuth 2.0 / SAML を話すアプリ向けのオープンソース ID 管理・アクセス制御サーバ。", category: "Identity & Policy", maturity: "Incubating" },
  { slug: "kserve", name: "KServe", tagline: "Kubernetes-native, multi-framework inference platform that turns a model into an autoscaling InferenceService for both predictive and generative AI.", taglineJa: "モデルを autoscaling な InferenceService CRD に変える、Kubernetes ネイティブでマルチフレームワークの推論基盤。予測 AI と生成 AI を 1 つのプラットフォームで扱う。", category: "Orchestration & Scheduling", maturity: "Incubating" },
  { slug: "kubeflow", name: "Kubeflow", tagline: "Orchestrates end-to-end machine learning workflows on Kubernetes by compiling pipeline definitions into Argo Workflows and tracking every run in ML Metadata.", taglineJa: "パイプライン定義を Argo Workflows にコンパイルし、すべての実行を ML Metadata で追跡して、エンドツーエンドの機械学習ワークフローを Kubernetes 上でオーケストレーションする。", category: "Orchestration & Scheduling", maturity: "Incubating" },
  { slug: "kubescape", name: "Kubescape", tagline: "Open-source Kubernetes security platform for misconfiguration, vulnerability, and runtime scanning from IDE to running cluster.", taglineJa: "IDE からクラスタまでをカバーする Kubernetes セキュリティの OSS プラットフォーム。構成・脆弱性・ランタイムを一気通貫でスキャンする。", category: "Security & Compliance", maturity: "Incubating" },
  { slug: "kubevela", name: "KubeVela", tagline: "Application-centric delivery control plane that turns one OAM Application into multi-cluster Kubernetes resources via composable CUE modules.", taglineJa: "1 つの OAM Application から、組み立て可能な CUE モジュール経由でマルチクラスタの Kubernetes リソースを配信するアプリ中心の control plane。", category: "App Definition & GitOps", maturity: "Incubating" },
  { slug: "kubevirt", name: "KubeVirt", tagline: "Run and manage KVM virtual machines as first-class Kubernetes workloads.", taglineJa: "KVM 仮想マシンを Kubernetes ネイティブなワークロードとして実行・管理する。", category: "Orchestration & Scheduling", maturity: "Incubating" },
  { slug: "lima", name: "Lima", tagline: "Linux virtual machines on macOS, Linux, and Windows with automatic file sharing and port forwarding.", taglineJa: "macOS / Linux / Windows 上で Linux 仮想マシンを起動し、ファイル共有とポートフォワードを自動化する。", category: "Runtime", maturity: "Incubating" },
  { slug: "litmus", name: "Litmus", tagline: "Cloud-native chaos engineering for Kubernetes, with a central control plane and a shared hub of reusable experiments.", taglineJa: "Kubernetes 向けのクラウドネイティブなカオスエンジニアリング。中央コントロールプレーンと、再利用可能な実験を共有する ChaosHub を備える。", category: "Chaos Engineering", maturity: "Incubating" },
  { slug: "longhorn", name: "Longhorn", tagline: "Kubernetes-native distributed block storage that gives every volume its own lightweight engine and replicas.", taglineJa: "ボリュームごとに専用エンジンとレプリカを持たせる、Kubernetes ネイティブの分散ブロックストレージ。", category: "Storage & Database", maturity: "Incubating" },
  { slug: "metal3-io", name: "metal3-io", tagline: "Kubernetes-native bare metal host provisioning that drives OpenStack Ironic through the BareMetalHost CRD.", taglineJa: "BareMetalHost CRD で OpenStack Ironic を駆動し、ベアメタルを Kubernetes ネイティブに払い出すプロビジョナ。", category: "Orchestration & Scheduling", maturity: "Incubating" },
  { slug: "microcks", name: "Microcks", tagline: "Spec-driven mock and contract-testing server: import an API artifact, get a live mock and contract tests from the same contract.", taglineJa: "仕様駆動のモック兼コントラクトテストサーバ。API アーティファクトを取り込むと、同じコントラクトからライブモックと契約テストが得られる。", category: "Developer Tools", maturity: "Incubating" },
  { slug: "nats", name: "NATS", tagline: "High-performance, single-binary messaging for cloud and edge, with optional JetStream persistence.", taglineJa: "クラウドとエッジ向けの高速な単一バイナリ・メッセージング基盤。JetStream で永続化も選べる。", category: "Messaging & Streaming", maturity: "Incubating" },
  { slug: "notary-project", name: "Notary Project", tagline: "Sign and verify OCI artifacts with X.509 PKI, storing portable signatures as OCI Referrers next to the artifact.", taglineJa: "X.509 PKI で OCI アーティファクトに署名・検証し、可搬な署名を OCI Referrer としてアーティファクトの隣に保存する。", category: "Supply Chain", maturity: "Incubating" },
  { slug: "opencost", name: "OpenCost", tagline: "Vendor-neutral CNCF spec and engine for real-time Kubernetes and cloud cost allocation.", taglineJa: "Kubernetes とクラウドのコストをリアルタイムに按分する、ベンダー中立な CNCF 仕様と実装。", category: "Observability", maturity: "Incubating" },
  { slug: "openfeature", name: "OpenFeature", tagline: "A vendor-neutral standard and reference daemon (flagd) for feature flag evaluation across any language and backend.", taglineJa: "言語やバックエンドを問わず使える、ベンダー中立な feature flag 評価の標準と参照実装 (flagd)。", category: "Developer Tools", maturity: "Incubating" },
  { slug: "openkruise", name: "OpenKruise", tagline: "Kubernetes controllers that extend the standard workloads and update container images in place without recreating Pods.", taglineJa: "Pod を再作成せずにコンテナイメージを差し替える Kubernetes ワークロード拡張コントローラ群。", category: "Orchestration & Scheduling", maturity: "Incubating" },
  { slug: "openyurt", name: "OpenYurt", tagline: "Extend a vanilla Kubernetes control plane to edge nodes with offline autonomy, keeping the upstream API intact.", taglineJa: "素の Kubernetes をそのまま使い、エッジノードにオフライン自律と地域分割を足すクラウドエッジ基盤。", category: "Orchestration & Scheduling", maturity: "Incubating" },
  { slug: "operator-framework", name: "Operator Framework", tagline: "Toolkit to build, package, and ship Kubernetes Operators in Go, Ansible, or Helm, wired into OLM for install and upgrades.", taglineJa: "Go / Ansible / Helm で Kubernetes Operator を作り、bundle 化して OLM 経由で配布・更新まで通すツールキット。", category: "App Definition & GitOps", maturity: "Incubating" },
  { slug: "strimzi", name: "Strimzi", tagline: "Run and operate Apache Kafka on Kubernetes through declarative custom resources and operators.", taglineJa: "Apache Kafka を宣言的なカスタムリソースと Operator で Kubernetes 上に構築・運用する。", category: "Messaging & Streaming", maturity: "Incubating" },
  { slug: "thanos", name: "Thanos", tagline: "Extends Prometheus with object-storage long-term retention and a single global query view across many servers.", taglineJa: "Prometheus を拡張し、オブジェクトストレージによる長期保存と複数サーバーをまたぐ単一のグローバルクエリビューを足す。", category: "Observability", maturity: "Incubating" },
  { slug: "volcano", name: "Volcano", tagline: "A Kubernetes-native batch scheduler that adds gang scheduling, queues, and fair-share to clusters running AI, ML, and big-data workloads.", taglineJa: "AI・ML・ビッグデータワークロードを動かすクラスタに、gang スケジューリング・キュー・フェアシェアを足す Kubernetes ネイティブなバッチスケジューラ。", category: "Orchestration & Scheduling", maturity: "Incubating" },
  { slug: "volcano-kthena", name: "Volcano-Kthena", tagline: "Kubernetes-native LLM inference orchestration that pairs Volcano gang scheduling with KV-cache-aware, prefill-decode routing.", taglineJa: "Volcano の gang scheduling と KV キャッシュ対応の prefill-decode ルーティングを組み合わせた、Kubernetes ネイティブな LLM 推論オーケストレータ。", category: "Orchestration & Scheduling", maturity: "Incubating" },
  { slug: "wasmcloud", name: "wasmCloud", tagline: "A WebAssembly component runtime that runs the same host locally and on Kubernetes, wiring components to swappable capability plugins.", taglineJa: "同じホストをローカルでも Kubernetes でも動かし、コンポーネントを差し替え可能な capability プラグインに結線する WebAssembly コンポーネントランタイム。", category: "Runtime", maturity: "Incubating" },
  { slug: "confidential-containers", name: "Confidential Containers", tagline: "Run unmodified Kubernetes Pods inside confidential VMs and release secrets only to workloads that pass remote attestation.", taglineJa: "無改変の Kubernetes Pod を confidential VM の中で動かし、リモート認証に合格したワークロードにだけシークレットを渡す。", category: "Security & Compliance", maturity: "Sandbox" },
  { slug: "athenz", name: "Athenz", tagline: "X.509 service identity and fine-grained RBAC for dynamic, hybrid-cloud infrastructure.", taglineJa: "動的・ハイブリッドクラウド向けの X.509 サービス認証ときめ細かい RBAC 認可基盤。", category: "Identity & Policy", maturity: "Sandbox" },
  { slug: "aeraki-mesh", name: "Aeraki Mesh", tagline: "A control plane that extends Istio to manage non-HTTP layer-7 protocols like Dubbo, Thrift, and Kafka in a service mesh.", taglineJa: "Dubbo・Thrift・Kafka など HTTP 以外の L7 プロトコルをサービスメッシュで扱えるよう Istio を拡張するコントロールプレーン。", category: "Service Mesh & Networking", maturity: "Sandbox" },
  { slug: "agones", name: "Agones", tagline: "Host, run, and scale dedicated multiplayer game servers on Kubernetes using custom resources and controllers.", taglineJa: "専用マルチプレイヤゲームサーバを、カスタムリソースとコントローラで Kubernetes 上にホスト・実行・スケールする。", category: "Orchestration & Scheduling", maturity: "Sandbox" },
  { slug: "akri", name: "Akri", tagline: "Discovers edge leaf devices (cameras, USB, OPC UA) and exposes them to Kubernetes as schedulable resources.", taglineJa: "エッジの leaf device (カメラ、USB、OPC UA) を発見し、Kubernetes にスケジュール可能なリソースとして公開する。", category: "Orchestration & Scheduling", maturity: "Sandbox" },
  { slug: "antrea", name: "Antrea", tagline: "A Kubernetes-native CNI that uses Open vSwitch as its data plane to provide pod networking and NetworkPolicy.", taglineJa: "Open vSwitch をデータプレーンに使い、Pod ネットワークと NetworkPolicy を提供する Kubernetes ネイティブな CNI。", category: "Service Mesh & Networking", maturity: "Sandbox" },
  { slug: "apicurio-registry", name: "Apicurio Registry", tagline: "A runtime server that stores, versions, and validates API definitions and event schemas, with pluggable storage backends.", taglineJa: "API 定義とイベントスキーマを保存・バージョン管理・検証するランタイムサーバ。ストレージバックエンドを差し替え可能。", category: "Messaging & Streaming", maturity: "Sandbox" },
  { slug: "armada", name: "Armada", tagline: "A high-throughput batch job scheduler that queues and schedules work across many Kubernetes clusters from outside the clusters themselves.", taglineJa: "多数の Kubernetes クラスタにまたがるバッチジョブを、クラスタ自体の外側でキューイング・スケジューリングする高スループットスケジューラ。", category: "Orchestration & Scheduling", maturity: "Sandbox" },
  { slug: "atlantis", name: "Atlantis", tagline: "A self-hosted server that runs Terraform and OpenTofu from pull request comments, planning and applying infrastructure in the open before merge.", taglineJa: "Pull Request のコメントから Terraform / OpenTofu を実行し、マージ前にインフラを公開の場で plan / apply するセルフホスト型サーバ。", category: "App Definition & GitOps", maturity: "Sandbox" },
  { slug: "bank-vaults", name: "Bank-Vaults", tagline: "Automates initializing, unsealing, and configuring HashiCorp Vault, keeping unseal keys encrypted with cloud KMS for Kubernetes.", taglineJa: "HashiCorp Vault の初期化・unseal・設定を自動化し、unseal キーをクラウド KMS で暗号化して保管する Kubernetes 向けツール群。", category: "Security & Compliance", maturity: "Sandbox" },
  { slug: "bfe", name: "BFE", tagline: "A Go layer-7 load balancer and reverse proxy from Baidu, with content-based routing via a human-readable condition DSL and two-stage GSLB/SLB load balancing.", taglineJa: "Baidu 発の Go 製レイヤ 7 ロードバランサ兼リバースプロキシ。人間が読める条件 DSL による内容ベースルーティングと、二段階の GSLB/SLB ロードバランスを備える。", category: "API Gateway", maturity: "Sandbox" },
  { slug: "bootc", name: "bootc", tagline: "Transactional, in-place operating system updates that ship the whole host as an OCI container image.", taglineJa: "ホスト OS 全体を OCI コンテナイメージとして配送し、トランザクショナルに in-place 更新する。", category: "Runtime", maturity: "Sandbox" },
  { slug: "bpfman", name: "bpfman", tagline: "An eBPF program manager that loads, attaches, and tracks eBPF programs on a node so applications avoid privileged kernel access.", taglineJa: "eBPF プログラムをノード上でロード・アタッチ・追跡するマネージャ。アプリのカーネルへの特権アクセスを不要にする。", category: "Runtime", maturity: "Sandbox" },
  { slug: "cadence-workflow", name: "Cadence Workflow", tagline: "A fault-tolerant, code-first orchestration engine that runs long-lived workflows and resumes them from event history after any crash.", taglineJa: "長時間動くワークフローを実行し、クラッシュ後も event history から復元して続行する、耐障害なコードファーストのオーケストレーションエンジン。", category: "Orchestration & Scheduling", maturity: "Sandbox" },
  { slug: "capsule", name: "Capsule", tagline: "Soft multi-tenancy for Kubernetes: group namespaces under a Tenant CRD and enforce isolation with admission webhooks.", taglineJa: "Kubernetes のソフトマルチテナンシー。複数の Namespace を Tenant CRD の下に束ね、admission webhook で分離を強制する。", category: "Identity & Policy", maturity: "Sandbox" },
  { slug: "carina", name: "Carina", tagline: "A CSI driver that carves local node disks into volumes with LVM, built for databases that want raw local disk performance.", taglineJa: "各ノードのローカルディスクを LVM でボリュームに切り出す CSI ドライバ。ローカルディスクの生性能を求めるデータベース向け。", category: "Storage & Database", maturity: "Sandbox" },
  { slug: "cartography", name: "Cartography", tagline: "Pulls cloud and SaaS assets and the relationships between them into a Neo4j graph so you can query exposure and access paths with Cypher.", taglineJa: "クラウドや SaaS の資産と資産どうしの関係を Neo4j グラフに取り込み、露出や到達経路を Cypher でクエリできるようにするセキュリティツール。", category: "Security & Compliance", maturity: "Sandbox" },
  { slug: "connect-rpc", name: "Connect RPC", tagline: "A Protocol Buffers RPC framework that generates typed clients and servers on plain net/http, so one server speaks the Connect protocol, gRPC, and gRPC-Web at once.", taglineJa: "Protocol Buffers から型付きクライアント・サーバを生成し、素の net/http 上で動く RPC フレームワーク。1 つのサーバが Connect 独自プロトコル・gRPC・gRPC-Web を同時に喋る。", category: "Developer Tools", maturity: "Sandbox" },
  { slug: "container2wasm", name: "container2wasm", tagline: "Converts a container image into a WebAssembly image that runs on a WASI runtime or in a browser, by compiling a CPU emulator to Wasm and running a real Linux plus runc inside it.", taglineJa: "CPU エミュレータを Wasm にコンパイルし、その中で本物の Linux と runc を動かすことで、コンテナイメージを WASI ランタイムやブラウザで動く WebAssembly イメージへ変換する。", category: "Runtime", maturity: "Sandbox" },
  { slug: "containerssh", name: "ContainerSSH", tagline: "An SSH server that boots a throwaway container for each connection and delegates authentication and per-connection configuration to external HTTP webhooks.", taglineJa: "接続ごとに使い捨てコンテナを起動し、認証と接続ごとの設定を外部 HTTP webhook に委譲する SSH サーバ。", category: "Developer Tools", maturity: "Sandbox" },
  { slug: "copa", name: "Copacetic", tagline: "Patches known OS-package vulnerabilities into an existing container image as an additive layer, driven by a scanner report, without a rebuild.", taglineJa: "スキャナのレポートを駆動源に、既知の OS パッケージ脆弱性を既存コンテナイメージへ追加レイヤーとして適用し、再ビルドなしでパッチする。", category: "Security & Compliance", maturity: "Sandbox" },
  { slug: "cozystack", name: "Cozystack", tagline: "A bare-metal private-cloud framework that serves managed Kubernetes, VMs, and databases as Flux HelmReleases through one aggregated API.", taglineJa: "ベアメタルに私設クラウドを作るフレームワーク。マネージド Kubernetes・VM・DB を単一の集約 API から Flux HelmRelease として提供する。", category: "App Definition & GitOps", maturity: "Sandbox" },
  { slug: "dalec", name: "Dalec", tagline: "Declarative YAML to native RPM/DEB packages and minimal, signed, SBOM-attested containers, using only Docker.", taglineJa: "YAML 1 枚から、ネイティブな RPM/DEB パッケージと、署名・SBOM 付きの最小コンテナを Docker だけでビルドする。", category: "Supply Chain", maturity: "Sandbox" },
  { slug: "devfile", name: "Devfile", tagline: "A YAML standard for cloud development workspaces, defined as Go types that generate every CRD, JSON schema, and TypeScript model.", taglineJa: "クラウド開発ワークスペースを宣言する YAML 標準。Go 型を単一の真実とし、CRD・JSON スキーマ・TypeScript モデルを生成する。", category: "Developer Tools", maturity: "Sandbox" },
  { slug: "devspace", name: "DevSpace", tagline: "A client-only CLI that runs your local code inside a Kubernetes pod and syncs edits both ways for in-cluster development.", taglineJa: "ローカルのコードを Kubernetes の Pod 内で動かし編集を双方向同期する、クラスタ内開発のためのクライアントオンリー CLI。", category: "Developer Tools", maturity: "Sandbox" },
  { slug: "dex", name: "Dex", tagline: "A federated OpenID Connect provider that delegates login to upstream identity providers like LDAP, SAML, GitHub, and Google.", taglineJa: "ログインを LDAP・SAML・GitHub・Google などの上流 ID プロバイダに委譲するフェデレーテッド OpenID Connect プロバイダ。", category: "Identity & Policy", maturity: "Sandbox" },
  { slug: "distribution", name: "Distribution", tagline: "The open-source registry that stores and serves container images, and the OCI Distribution core many registries build on.", taglineJa: "コンテナイメージを保存・配信するオープンソースレジストリ。多くのレジストリが土台とする OCI Distribution のコア。", category: "Container Registry", maturity: "Sandbox" },
  { slug: "drasi", name: "Drasi", tagline: "Detect changes across data sources with standing Cypher queries and fire reactions, without copying or polling the data.", taglineJa: "データソースの変更を常駐 Cypher クエリで検知し、データをコピーもポーリングもせずにリアクションを発火させる。", category: "Messaging & Streaming", maturity: "Sandbox" },
  { slug: "easegress", name: "Easegress", tagline: "A Go traffic gateway with a result-driven filter pipeline and embedded etcd for self-contained HA.", taglineJa: "result 駆動の filter pipeline と埋め込み etcd で自己完結する HA を持つ Go 製トラフィックゲートウェイ。", category: "API Gateway", maturity: "Sandbox" },
  { slug: "eraser", name: "Eraser", tagline: "Deletes vulnerable and unwanted container images from every Kubernetes node, never touching images a running container uses.", taglineJa: "脆弱・不要なコンテナイメージを全 Kubernetes ノードから削除し、実行中コンテナが使うイメージには触れない。", category: "Security & Compliance", maturity: "Sandbox" },
  { slug: "external-secrets", name: "External Secrets Operator", tagline: "Syncs secrets from external managers like AWS, Vault, and GCP into native Kubernetes Secrets.", taglineJa: "AWS・Vault・GCP などの外部シークレットマネージャの値をネイティブな Kubernetes Secret に同期する。", category: "Security & Compliance", maturity: "Sandbox" },
  { slug: "hami", name: "HAMi", tagline: "Share one physical GPU across Kubernetes pods by memory and compute, with per-pod limits enforced at runtime and no application changes.", taglineJa: "1 枚の物理 GPU を Kubernetes の Pod 間でメモリと演算で分割共有し、Pod ごとの上限を実行時に強制する。アプリ改変は不要。", category: "Orchestration & Scheduling", maturity: "Incubating" },
  { slug: "headlamp", name: "Headlamp", tagline: "An extensible web and desktop UI for Kubernetes that proxies every cluster API through its own backend and loads plugins at runtime.", taglineJa: "あらゆるクラスタ API を自前バックエンド経由でプロキシし、プラグインを実行時にロードする拡張可能な Kubernetes 向け Web / デスクトップ UI。", category: "Developer Tools", maturity: "Sandbox" },
  { slug: "higress", name: "Higress", tagline: "An API gateway that embeds a forked Istio Pilot to turn Ingress and nginx annotations into Envoy config, with a Wasm plugin layer for AI and traffic.", taglineJa: "フォークした Istio Pilot を内蔵し、Ingress と nginx アノテーションを Envoy 設定に変える API ゲートウェイ。AI・トラフィック向けの Wasm プラグイン層を持つ。", category: "API Gateway", maturity: "Sandbox" },
  { slug: "holmesgpt", name: "HolmesGPT", tagline: "An AI agent that investigates production incidents by driving read-only observability tools through a controlled LLM loop.", taglineJa: "read-only な observability ツールを制御された LLM ループで駆動し本番インシデントを調査する AI エージェント。", category: "Observability", maturity: "Sandbox" },
]
